# Dockerfile, Docker Image, Docker Container

# Dockerfile - Blueprint for Docker Image
# Docker Image - Template for running Docker Container 
# Docker Container - Actual running process

FROM python:3.8

ADD main.py .

RUN pip install requests beautifulsoup4

CMD ["python", "main.py"]

